server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallery
    username: root
    password: kyungmin_root


  redis:
    host: localhost
    port: 6379

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

