server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallery
    username: root
    password: kyungmin_root

    # url: jdbc:mysql://mallery4.c1uvd651eczi.ap-northeast-2.rds.amazonaws.com/mallery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # username: admin
    # password: graduation2023

  redis:
    host: localhost
    port: 6379

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

