server:
  port: 8080

spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/graduation
    url: jdbc:mysql://mallery4.csmtzvyurww1.us-east-1.rds.amazonaws.com:3306/mallery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mallery
    password: graduation2023
    # username: root
    # password: kyungmin_root

  redis:
    host: localhost
    port: 6379

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
